### ISSUE TITLE
Some docs/help

### ISSUE THREAD

**Issue by etshy** [odahcam/TurnJS#1]
Hi
I took a look at your fork, and it seems to be the most recent build of turnjs (for now, I didn't look al the 18XX forks)

Do you have a list of all the features you added ?
Or do you plan creating docs for these ?

If there is some interestings features, I'll take your fork, instead of the "official" build.

**Comment by odahcam** [comment]
Well, I was doing a rewrite job, but I ran out of time. I heard about a fork called FlippyJS or something like that, that is in a way more advanced than my fork. 

Unfurtunately, I have no plans of get back to work here again and I only added some responsibility to the component, nothing else I can remember.

**Comment by etshy** [comment]
Ok thanks.
there are several plugin named flippyjs but I found it
(this one : https://github.com/marvindanig/flippy.JS right?)

Thanks a lot for the info.

**Comment by odahcam** [comment]
You're welcome. You found the right repo. Good luck.
